server.port: 8083
spring:
  h2.console.enabled: true
  datasource:
    name: SYNOPTICDATADB
    url: jdbc:h2:file:D:/h2/SynopticDataDB
    driver-class-name: org.h2.Driver
    username: sa
    password: password
    generate-unique-name: false
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate.ddl-auto: update
    show-sql: true
    properties.hibernate:
      format: true
      dialect: org.hibernate.dialect.H2Dialect

logging:
  level:
    root: INFO
    pl.ideopolis.webScraperTge: INFO
#  file:
#  file.max-size:
#  file.max-history:
#  path:

